import { Bar } from 'react-chartjs-2';

const getTipsMetadata = (source) => {
    switch (source) {
        case 'gemini':
            return {
                badge: 'Gemini AI',
                description:
                    'Personalized recommendations generated using Gemini AI.',
            };

        case 'fallback':
            return {
                badge: 'Built-in Eco Coach',
                description:
                    'Reliable recommendations generated by the built-in sustainability engine.',
            };

        case 'loading':
            return {
                badge: 'Preparing',
                description:
                    'Your personalized eco action plan is being prepared.',
            };

        default:
            return {
                badge: null,
                description:
                    'The recommendation service is temporarily unavailable.',
            };
    }
};

const ResultsPanel = ({
    footprintData,
    chartData,
    tips,
    tipsSource,
}) => {
    const tipsMetadata = getTipsMetadata(tipsSource);

    return (
        <div>
            {footprintData && (
                <>
                    <div className="bg-green-100 p-6 rounded-lg">
                        <h2 className="text-2xl font-semibold text-gray-700 mb-4">
                            Your Carbon Score
                        </h2>

                        <p className="text-5xl font-bold text-green-700 text-center">
                            {footprintData.total_footprint.toFixed(2)}
                        </p>

                        <p className="text-lg text-gray-600 text-center">
                            kg CO2e
                        </p>
                    </div>

                    {footprintData?.insight && (
                        <div className="mt-6 rounded-lg border border-blue-200 bg-blue-50 p-5">
                            <div className="flex flex-wrap items-center justify-between gap-3">
                                <h2 className="text-xl font-semibold text-gray-700">
                                    Smart Carbon Insight
                                </h2>

                                <span className="rounded-full bg-white px-3 py-1 text-xs font-semibold uppercase text-blue-700">
                                    {footprintData.insight.impact_level} impact
                                </span>
                            </div>

                            <p className="mt-3 text-gray-700">
                                {footprintData.insight.message}
                            </p>
                        </div>
                    )}
                    {footprintData?.insight?.target_reduction_percent > 0 && (
                        <div className="mt-4 rounded-lg border border-emerald-200 bg-emerald-50 p-5">
                            <h3 className="text-lg font-semibold text-gray-700">
                                Your Next Reduction Goal
                            </h3>

                            <p className="mt-2 text-gray-700">
                                Aim to reduce your footprint by{' '}
                                <span className="font-bold text-emerald-700">
                                    {footprintData.insight.target_reduction_percent}%
                                </span>
                                .
                            </p>

                            <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">
                                <div className="rounded-md bg-white p-3">
                                    <p className="text-xs font-medium uppercase text-gray-500">
                                        Potential saving
                                    </p>

                                    <p className="mt-1 text-xl font-bold text-emerald-700">
                                        {footprintData.insight.potential_savings.toFixed(2)} kg CO2e
                                    </p>
                                </div>

                                <div className="rounded-md bg-white p-3">
                                    <p className="text-xs font-medium uppercase text-gray-500">
                                        Target footprint
                                    </p>

                                    <p className="mt-1 text-xl font-bold text-emerald-700">
                                        {footprintData.insight.target_footprint.toFixed(2)} kg CO2e
                                    </p>
                                </div>
                            </div>
                        </div>
                    )}
                    <div className="mt-8">
                        <h2 className="text-2xl font-semibold text-gray-700 mb-4">
                            Footprint Breakdown
                        </h2>

                        <Bar data={chartData} />
                    </div>
                </>
            )}

            {tips && (
                <section
                    className="mt-8 bg-yellow-100 p-6 rounded-lg"
                    aria-live="polite"
                    aria-busy={tipsSource === 'loading'}
                >
                    <div className="flex items-center justify-between gap-3 mb-3">
                        <h2 className="text-2xl font-semibold text-gray-700">
                            Personalized Eco Action Plan
                        </h2>

                        {tipsMetadata.badge && (
                            <span className="text-xs font-semibold px-3 py-1 rounded-full bg-white text-gray-600">
                                {tipsMetadata.badge}
                            </span>
                        )}
                    </div>

                    <p className="text-sm text-gray-600 mb-4">
                        {tipsMetadata.description}
                    </p>

                    <div className="text-gray-800 whitespace-pre-wrap">
                        {tips}
                    </div>
                </section>
            )}
        </div>
    );
};

export default ResultsPanel;